### ISSUE TITLE
Fix `LocalStorage` always adding the Range header

### ISSUE THREAD

**Issue by CastilloDel** [chris-zen/htsget-rs#26]
Right now the implementation of `LocalStorage` always adds the `Range` header to the url. It shouldn't be adding the header unless it is necessary. For more context look at the discussion in [this PR](https://github.com/chris-zen/htsget-mvp/pull/22#discussion_r613163420)

**Comment by CastilloDel** [comment]
I have one doubt on how to proceed with this. @brainstorm I was reading [what you sent](https://datatracker.ietf.org/doc/html/rfc7233#section-2.1) in #22. And I understand that a byte range like `-3` would represent the last 3 bytes.
```
 Additional examples, assuming a representation of length 10000:

   o  The final 500 bytes (byte offsets 9500-9999, inclusive):

        bytes=-500

   Or:

        bytes=9500-
```
This is different than what happens in out byte ranges, where `-3` would mean the bytes before three (not inclusive). If I understand correctly our `BytesRange` mimics noodles. I guess there has to be a small transformation when using `BytesRange` in the Url. Correct me if I¡m wrong

**Comment by brainstorm** [comment]
Ah, yeah, good catch! Make sure you stick to htsget spec instead of the RFC I referred, sorry for the confusion!
